pub mod alt_tab;
pub mod appearance;
pub mod audio;
pub mod bookmarks;
pub mod claude;
pub mod clipboard;
pub mod codex;
pub mod config;
pub mod deeplink;
// Linux-only (not merely non-Windows): pulls in gtk/gio, which macOS lacks.
#[cfg(target_os = "linux")]
pub mod desktop;
pub mod explorer;
pub mod file_index;
pub mod fs;
pub mod icons;
pub mod launcher;
#[cfg(target_os = "linux")]
pub mod linux_shortcuts;
pub mod process;
pub mod rates;
pub mod screenshot;
pub mod search;
pub mod shortcuts;
pub mod paste;
pub mod stats;
pub mod store;
pub mod system;
pub mod window;
pub mod window_drag;
